name = "vfe34"
pages_build_output_dir = "./dist"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "VFDashboard"
id = "dae5424266fa46ba83eed605ae668e5a"
